-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP TYPE public."dispute_status";

CREATE TYPE public."dispute_status" AS ENUM (
	'OPEN',
	'UNDER_REVIEW',
	'RESOLVED',
	'CLOSED');

-- DROP TYPE public."escrow_status";

CREATE TYPE public."escrow_status" AS ENUM (
	'LOCKED',
	'RELEASED',
	'REFUNDED',
	'DISPUTED');

-- DROP TYPE public."file_entity_type";

CREATE TYPE public."file_entity_type" AS ENUM (
	'JOB',
	'PROPOSAL',
	'PROJECT',
	'MILESTONE');

-- DROP TYPE public."job_status";

CREATE TYPE public."job_status" AS ENUM (
	'OPEN',
	'CLOSED',
	'CANCELLED');

-- DROP TYPE public."milestone_status";

CREATE TYPE public."milestone_status" AS ENUM (
	'PENDING',
	'IN_PROGRESS',
	'SUBMITTED',
	'APPROVED',
	'REJECTED',
	'RELEASED');

-- DROP TYPE public."project_status";

CREATE TYPE public."project_status" AS ENUM (
	'DRAFT',
	'IN_PROGRESS',
	'COMPLETED',
	'CANCELLED',
	'DISPUTED');

-- DROP TYPE public."project_type";

CREATE TYPE public."project_type" AS ENUM (
	'FIXED_PRICE',
	'HOURLY');

-- DROP TYPE public."proposal_status";

CREATE TYPE public."proposal_status" AS ENUM (
	'PENDING',
	'ACCEPTED',
	'REJECTED',
	'WITHDRAWN',
	'SHORTLISTED',
	'AWARDED');

-- DROP TYPE public."user_role";

CREATE TYPE public."user_role" AS ENUM (
	'USER',
	'ADMIN',
	'FREELANCER',
	'EMPLOYER');

-- DROP SEQUENCE audit_logs_id_seq;

CREATE SEQUENCE audit_logs_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE child_wallet_pool_id_seq;

CREATE SEQUENCE child_wallet_pool_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE gas_topups_id_seq;

CREATE SEQUENCE gas_topups_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE hd_master_wallet_id_seq;

CREATE SEQUENCE hd_master_wallet_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE token_sweeps_id_seq;

CREATE SEQUENCE token_sweeps_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE wallet_transactions_id_seq;

CREATE SEQUENCE wallet_transactions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE withdrawal_transactions_id_seq;

CREATE SEQUENCE withdrawal_transactions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.hd_master_wallet definition

-- Drop table

-- DROP TABLE hd_master_wallet;

CREATE TABLE hd_master_wallet (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	encrypted_mnemonic varchar(255) NOT NULL,
	master_address varchar(64) NULL,
	CONSTRAINT hd_master_wallet_pkey PRIMARY KEY (id)
);


-- public.notifications definition

-- Drop table

-- DROP TABLE notifications;

CREATE TABLE notifications (
	id uuid NOT NULL,
	created_at timestamp(6) NULL,
	entity_id uuid NULL,
	entity_type varchar(255) NULL,
	is_read bool NULL,
	message text NULL,
	read_at timestamp(6) NULL,
	title varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	user_id uuid NOT NULL,
	CONSTRAINT notifications_pkey PRIMARY KEY (id),
	CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT_SUCCESS'::character varying, 'WITHDRAWAL_SUCCESS'::character varying, 'WITHDRAWAL_PENDING'::character varying, 'JOB_POSTED'::character varying, 'PROPOSAL_RECEIVED'::character varying, 'PROPOSAL_ACCEPTED'::character varying, 'PROJECT_STARTED'::character varying, 'MILESTONE_CREATED'::character varying, 'MILESTONE_SUBMITTED'::character varying, 'MILESTONE_APPROVED'::character varying, 'MILESTONE_REJECTED'::character varying, 'PAYMENT_RECEIVED'::character varying, 'PAYMENT_SENT'::character varying, 'DISPUTE_OPENED'::character varying, 'DISPUTE_RESOLVED'::character varying, 'MESSAGE_RECEIVED'::character varying, 'SYSTEM_ALERT'::character varying])::text[])))
);


-- public.skills definition

-- Drop table

-- DROP TABLE skills;

CREATE TABLE skills (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT skills_name_key UNIQUE (name),
	CONSTRAINT skills_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	id uuid NOT NULL,
	address varchar(255) NULL,
	avatar varchar(255) NULL,
	birthday varchar(255) NULL,
	code varchar(255) NULL,
	date_created timestamp(6) NULL,
	date_updated timestamp(6) NULL,
	description varchar(255) NULL,
	device_id varchar(255) NULL,
	email varchar(255) NULL,
	full_name varchar(255) NULL,
	gender varchar(255) NULL,
	is_active bool NOT NULL,
	is_admin bool NOT NULL,
	is_user bool NOT NULL,
	"password" varchar(255) NULL,
	phone varchar(255) NULL,
	"role" varchar(255) NULL,
	salt varchar(255) NULL,
	secret_key varchar(255) NULL,
	status int4 NOT NULL,
	user_created varchar(255) NULL,
	user_updated varchar(255) NULL,
	username varchar(255) NULL,
	city varchar(50) NULL,
	country varchar(50) NULL,
	password_changed_at timestamp(6) NULL,
	withdrawals_disabled_until timestamp(6) NULL,
	two_factor_enabled bool NULL,
	two_factor_enabled_at timestamp(6) NULL,
	two_factor_secret varchar(255) NULL,
	two_factor_temp_secret varchar(255) NULL,
	CONSTRAINT uq_users_email UNIQUE (email),
	CONSTRAINT uq_users_username UNIQUE (username),
	CONSTRAINT users_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'UNKNOWN'::character varying])::text[]))),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY['USER'::text, 'ADMIN'::text, 'FREELANCER'::text, 'EMPLOYER'::text])))
);
CREATE INDEX idx_email ON public.users USING btree (email);
CREATE INDEX idx_phone ON public.users USING btree (phone);
CREATE INDEX idx_username ON public.users USING btree (username);


-- public.withdrawal_transactions definition

-- Drop table

-- DROP TABLE withdrawal_transactions;

CREATE TABLE withdrawal_transactions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(36, 18) NOT NULL,
	block_number int8 NULL,
	confirmations int4 NULL,
	confirmed_at timestamp(6) NULL,
	created_at timestamp(6) NULL,
	failure_reason varchar(255) NULL,
	fee numeric(36, 18) NOT NULL,
	max_retries int4 NULL,
	net_amount numeric(36, 18) NOT NULL,
	processed_at timestamp(6) NULL,
	retry_count int4 NULL,
	status varchar(255) NOT NULL,
	to_address varchar(255) NOT NULL,
	tx_hash varchar(255) NULL,
	updated_at timestamp(6) NULL,
	user_id uuid NOT NULL,
	user_confirmed_at timestamp(6) NULL,
	CONSTRAINT withdrawal_transactions_pkey PRIMARY KEY (id),
	CONSTRAINT withdrawal_transactions_status_check CHECK (((status)::text = ANY (ARRAY[('CREATED'::character varying)::text, ('PENDING'::character varying)::text, ('PROCESSING'::character varying)::text, ('BROADCASTING'::character varying)::text, ('SENT'::character varying)::text, ('CONFIRMED'::character varying)::text, ('FAILED'::character varying)::text, ('CANCELLED'::character varying)::text])))
);
CREATE INDEX idx_withdraw_user_created ON public.withdrawal_transactions USING btree (user_id, created_at);


-- public.audit_logs definition

-- Drop table

-- DROP TABLE audit_logs;

CREATE TABLE audit_logs (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"action" varchar(255) NOT NULL,
	details text NULL,
	entity_id varchar(255) NULL,
	entity_type varchar(255) NOT NULL,
	error_message varchar(255) NULL,
	ip_address varchar(255) NULL,
	success bool NULL,
	"timestamp" timestamp(6) NOT NULL,
	user_agent varchar(255) NULL,
	user_id uuid NULL,
	CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
	CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_audit_logs_user_time ON public.audit_logs USING btree (user_id, "timestamp");


-- public.child_wallet_pool definition

-- Drop table

-- DROP TABLE child_wallet_pool;

CREATE TABLE child_wallet_pool (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address varchar(64) NOT NULL,
	created_at timestamp(6) NULL,
	derivation_index int4 NOT NULL,
	first_deposit_at timestamp(6) NULL,
	status varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	user_id uuid NULL,
	CONSTRAINT child_wallet_pool_pkey PRIMARY KEY (id),
	CONSTRAINT child_wallet_pool_status_check CHECK (((status)::text = ANY ((ARRAY['FREE'::character varying, 'ASSIGNED'::character varying, 'ACTIVE'::character varying, 'RETIRED'::character varying])::text[]))),
	CONSTRAINT uklx7xcnqhjk7o4a1jp3qjgwxjb UNIQUE (address),
	CONSTRAINT ukr3ma2l4u8ku89g2io9axio3td UNIQUE (derivation_index),
	CONSTRAINT fk_child_wallet_user FOREIGN KEY (user_id) REFERENCES users(id)
);


-- public.employer_profiles definition

-- Drop table

-- DROP TABLE employer_profiles;

CREATE TABLE employer_profiles (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	user_id uuid NOT NULL,
	company_name varchar(255) NULL,
	company_website varchar(255) NULL,
	company_size varchar(255) NULL,
	industry varchar(255) NULL,
	jobs_posted int4 DEFAULT 0 NULL,
	active_projects int4 DEFAULT 0 NULL,
	total_spent numeric(38, 2) DEFAULT 0 NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	CONSTRAINT employer_profiles_pkey PRIMARY KEY (id),
	CONSTRAINT employer_profiles_user_id_key UNIQUE (user_id),
	CONSTRAINT employer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_employer_profiles_user_id ON public.employer_profiles USING btree (user_id);


-- public.files definition

-- Drop table

-- DROP TABLE files;

CREATE TABLE files (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	uploaded_by uuid NOT NULL,
	entity_type public."file_entity_type" NOT NULL,
	entity_id uuid NOT NULL,
	file_url text NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT files_pkey PRIMARY KEY (id),
	CONSTRAINT files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id)
);
CREATE INDEX idx_files_entity ON public.files USING btree (entity_type, entity_id);


-- public.freelancer_profiles definition

-- Drop table

-- DROP TABLE freelancer_profiles;

CREATE TABLE freelancer_profiles (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	user_id uuid NOT NULL,
	professional_title varchar(255) NULL,
	bio text NULL,
	hourly_rate numeric(38, 2) NULL,
	availability varchar(255) DEFAULT 'AVAILABLE'::character varying NULL,
	total_earnings numeric(38, 2) DEFAULT 0 NULL,
	jobs_completed int4 DEFAULT 0 NULL,
	avg_rating numeric(38, 2) DEFAULT 0 NULL,
	portfolio_url varchar(255) NULL,
	github_url varchar(255) NULL,
	linkedin_url varchar(255) NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	CONSTRAINT freelancer_profiles_pkey PRIMARY KEY (id),
	CONSTRAINT freelancer_profiles_user_id_key UNIQUE (user_id),
	CONSTRAINT freelancer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_freelancer_profiles_user_id ON public.freelancer_profiles USING btree (user_id);


-- public.freelancer_skills definition

-- Drop table

-- DROP TABLE freelancer_skills;

CREATE TABLE freelancer_skills (
	freelancer_profile_id uuid NOT NULL,
	skill_id uuid NOT NULL,
	proficiency_level varchar(20) DEFAULT 'INTERMEDIATE'::character varying NULL,
	years_experience int4 DEFAULT 0 NULL,
	CONSTRAINT freelancer_skills_pkey PRIMARY KEY (freelancer_profile_id, skill_id),
	CONSTRAINT freelancer_skills_freelancer_profile_id_fkey FOREIGN KEY (freelancer_profile_id) REFERENCES freelancer_profiles(id) ON DELETE CASCADE,
	CONSTRAINT freelancer_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);


-- public.gas_topups definition

-- Drop table

-- DROP TABLE gas_topups;

CREATE TABLE gas_topups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount_trx numeric(30, 6) NOT NULL,
	child_index int4 NOT NULL,
	created_at timestamp(6) NULL,
	status varchar(255) NULL,
	tx_hash varchar(128) NULL,
	child_wallet_id int8 NULL,
	CONSTRAINT gas_topups_pkey PRIMARY KEY (id),
	CONSTRAINT gas_topups_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'CONFIRMED'::character varying, 'FAILED'::character varying])::text[]))),
	CONSTRAINT fk_gas_child FOREIGN KEY (child_wallet_id) REFERENCES child_wallet_pool(id)
);
CREATE INDEX idx_gas_topups_child ON public.gas_topups USING btree (child_wallet_id);


-- public.jobs definition

-- Drop table

-- DROP TABLE jobs;

CREATE TABLE jobs (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	employer_id uuid NOT NULL,
	title varchar(500) NOT NULL,
	description text NOT NULL,
	job_type varchar(255) NOT NULL,
	currency varchar(10) DEFAULT 'USDT'::character varying NULL,
	required_skills text NULL,
	deadline date NULL,
	status varchar(255) DEFAULT 'OPEN'::job_status NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	budget numeric(20, 2) NOT NULL,
	duration varchar(100) NULL,
	"type" varchar(255) NOT NULL,
	complexity varchar(255) DEFAULT 'SMALL'::character varying NULL,
	estimated_milestones int4 NULL,
	budget_max numeric(12, 2) NULL,
	budget_min numeric(12, 2) NULL,
	CONSTRAINT jobs_pkey PRIMARY KEY (id),
	CONSTRAINT jobs_type_check CHECK (((type)::text = ANY ((ARRAY['FIXED_PRICE'::character varying, 'HOURLY'::character varying])::text[]))),
	CONSTRAINT jobs_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES users(id)
);
CREATE INDEX idx_jobs_employer_id ON public.jobs USING btree (employer_id);
CREATE INDEX idx_jobs_status ON public.jobs USING btree (status);


-- public.proposals definition

-- Drop table

-- DROP TABLE proposals;

CREATE TABLE proposals (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	job_id uuid NOT NULL,
	freelancer_id uuid NOT NULL,
	cover_letter text NOT NULL,
	proposed_amount numeric(12, 2) NOT NULL,
	estimated_duration_days int4 NULL,
	status varchar(255) DEFAULT 'PENDING'::proposal_status NULL,
	accepted_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	CONSTRAINT proposals_pkey PRIMARY KEY (id),
	CONSTRAINT uq_proposal_per_job UNIQUE (job_id, freelancer_id),
	CONSTRAINT proposals_freelancer_id_fkey FOREIGN KEY (freelancer_id) REFERENCES users(id),
	CONSTRAINT proposals_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
CREATE INDEX idx_proposals_freelancer_id ON public.proposals USING btree (freelancer_id);
CREATE INDEX idx_proposals_job_id ON public.proposals USING btree (job_id);
CREATE INDEX idx_proposals_status ON public.proposals USING btree (status);


-- public.token_sweeps definition

-- Drop table

-- DROP TABLE token_sweeps;

CREATE TABLE token_sweeps (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(36, 6) NOT NULL,
	child_address varchar(64) NOT NULL,
	child_index int4 NOT NULL,
	created_at timestamp(6) NULL,
	error_message varchar(255) NULL,
	master_address varchar(64) NOT NULL,
	retry_count int4 NULL,
	status varchar(255) NULL,
	sweep_tx_hash varchar(128) NULL,
	updated_at timestamp(6) NULL,
	child_wallet_id int8 NULL,
	CONSTRAINT token_sweeps_pkey PRIMARY KEY (id),
	CONSTRAINT token_sweeps_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'CONFIRMED'::character varying, 'FAILED'::character varying])::text[]))),
	CONSTRAINT fk_sweep_child FOREIGN KEY (child_wallet_id) REFERENCES child_wallet_pool(id)
);
CREATE INDEX idx_token_sweeps_child ON public.token_sweeps USING btree (child_wallet_id);


-- public.wallet_transactions definition

-- Drop table

-- DROP TABLE wallet_transactions;

CREATE TABLE wallet_transactions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(36, 18) NOT NULL,
	block_number int8 NULL,
	block_timestamp timestamp(6) NULL,
	confirmation_count int4 NULL,
	created_at timestamp(6) NULL,
	direction varchar(255) NOT NULL,
	error_message varchar(255) NULL,
	from_address varchar(255) NOT NULL,
	gas_price numeric(38, 2) NULL,
	gas_used numeric(38, 2) NULL,
	is_swept bool NOT NULL,
	points_credited numeric(38, 2) NULL,
	points_credited_at timestamp(6) NULL,
	status varchar(255) NOT NULL,
	sweep_tx_hash varchar(255) NULL,
	swept_at timestamp(6) NULL,
	to_address varchar(255) NOT NULL,
	token_address varchar(255) NULL,
	transaction_type varchar(255) NOT NULL,
	tx_hash varchar(255) NOT NULL,
	updated_at timestamp(6) NULL,
	confirmed_at timestamp(6) NULL,
	"type" varchar(255) NULL,
	wallet_address varchar(255) NULL,
	child_wallet_id int8 NULL,
	user_id uuid NULL,
	CONSTRAINT uks6vuutjlf7t1ny0tlgwchpjp UNIQUE (tx_hash),
	CONSTRAINT wallet_transactions_direction_check CHECK (((direction)::text = ANY ((ARRAY['IN'::character varying, 'OUT'::character varying])::text[]))),
	CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
	CONSTRAINT wallet_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'FAILED'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying])::text[]))),
	CONSTRAINT wallet_transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'SWEEP'::character varying, 'WITHDRAWAL'::character varying, 'INTERNAL_TRANSFER'::character varying])::text[]))),
	CONSTRAINT fk_wallet_tx_child FOREIGN KEY (child_wallet_id) REFERENCES child_wallet_pool(id),
	CONSTRAINT fk_wallet_tx_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_wallet_tx_child ON public.wallet_transactions USING btree (child_wallet_id);
CREATE INDEX idx_wallet_tx_type_status ON public.wallet_transactions USING btree (transaction_type, status);
CREATE INDEX idx_wallet_tx_user_created ON public.wallet_transactions USING btree (user_id, created_at);


-- public.job_skills definition

-- Drop table

-- DROP TABLE job_skills;

CREATE TABLE job_skills (
	job_id uuid NOT NULL,
	skill_id uuid NOT NULL,
	CONSTRAINT job_skills_pkey PRIMARY KEY (job_id, skill_id),
	CONSTRAINT job_skills_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
	CONSTRAINT job_skills_skill_id_fkey FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);


-- public.points_ledger definition

-- Drop table

-- DROP TABLE points_ledger;

CREATE TABLE points_ledger (
	id varchar(36) NOT NULL,
	amount numeric(36, 18) NOT NULL,
	balance_after numeric(36, 18) NOT NULL,
	balance_before numeric(36, 18) NOT NULL,
	created_at timestamp(6) NULL,
	description varchar(255) NULL,
	exchange_rate numeric(18, 8) NULL,
	reference_id varchar(255) NULL,
	status varchar(255) NOT NULL,
	transaction_id varchar(255) NULL,
	transaction_type varchar(255) NOT NULL,
	usdt_amount numeric(36, 18) NULL,
	user_id uuid NULL,
	from_user_id uuid NULL,
	to_user_id uuid NULL,
	wallet_transaction_id int8 NULL,
	withdrawal_id int8 NULL,
	CONSTRAINT points_ledger_pkey PRIMARY KEY (id),
	CONSTRAINT points_ledger_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT points_ledger_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['DEPOSIT_CREDIT'::character varying, 'P2P_SEND'::character varying, 'P2P_RECEIVE'::character varying, 'WITHDRAWAL_DEBIT'::character varying, 'ESCROW_LOCK'::character varying, 'ESCROW_RELEASE'::character varying, 'ESCROW_REFUND'::character varying, 'ADJUSTMENT'::character varying, 'BONUS'::character varying, 'REFUND'::character varying])::text[]))),
	CONSTRAINT fk_pl_from_user FOREIGN KEY (from_user_id) REFERENCES users(id),
	CONSTRAINT fk_pl_to_user FOREIGN KEY (to_user_id) REFERENCES users(id),
	CONSTRAINT fk_pl_user FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT fk_pl_withdraw FOREIGN KEY (withdrawal_id) REFERENCES withdrawal_transactions(id),
	CONSTRAINT fk_pl_wtx FOREIGN KEY (wallet_transaction_id) REFERENCES wallet_transactions(id)
);
CREATE INDEX idx_pl_user_created ON public.points_ledger USING btree (user_id, created_at);


-- public.projects definition

-- Drop table

-- DROP TABLE projects;

CREATE TABLE projects (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	job_id uuid NOT NULL,
	employer_id uuid NOT NULL,
	freelancer_id uuid NOT NULL,
	awarded_proposal_id uuid NOT NULL,
	agreed_amount numeric(15, 2) NOT NULL,
	currency varchar(10) DEFAULT 'USDT'::character varying NULL,
	status varchar(255) DEFAULT 'IN_PROGRESS'::project_status NULL,
	started_at timestamptz NULL,
	completed_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	CONSTRAINT projects_pkey PRIMARY KEY (id),
	CONSTRAINT projects_awarded_proposal_id_fkey FOREIGN KEY (awarded_proposal_id) REFERENCES proposals(id) ON DELETE CASCADE,
	CONSTRAINT projects_employer_id_fkey FOREIGN KEY (employer_id) REFERENCES users(id),
	CONSTRAINT projects_freelancer_id_fkey FOREIGN KEY (freelancer_id) REFERENCES users(id),
	CONSTRAINT projects_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
CREATE INDEX idx_projects_employer_id ON public.projects USING btree (employer_id);
CREATE INDEX idx_projects_freelancer_id ON public.projects USING btree (freelancer_id);
CREATE INDEX idx_projects_job_id ON public.projects USING btree (job_id);
CREATE INDEX idx_projects_status ON public.projects USING btree (status);


-- public.reviews definition

-- Drop table

-- DROP TABLE reviews;

CREATE TABLE reviews (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	project_id uuid NOT NULL,
	reviewer_id uuid NOT NULL,
	reviewee_id uuid NOT NULL,
	rating int4 NOT NULL,
	"comment" text NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT reviews_pkey PRIMARY KEY (id),
	CONSTRAINT reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5))),
	CONSTRAINT uq_review_per_project UNIQUE (project_id, reviewer_id, reviewee_id),
	CONSTRAINT reviews_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id),
	CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES users(id),
	CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES users(id)
);
CREATE INDEX idx_reviews_reviewee_id ON public.reviews USING btree (reviewee_id);


-- public.conversations definition

-- Drop table

-- DROP TABLE conversations;

CREATE TABLE conversations (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	job_id uuid NULL,
	project_id uuid NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT chk_job_or_project CHECK (((job_id IS NOT NULL) OR (project_id IS NOT NULL))),
	CONSTRAINT conversations_pkey PRIMARY KEY (id),
	CONSTRAINT conversations_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs(id),
	CONSTRAINT conversations_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id)
);


-- public.disputes definition

-- Drop table

-- DROP TABLE disputes;

CREATE TABLE disputes (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	project_id uuid NOT NULL,
	raised_by uuid NOT NULL,
	reason text NOT NULL,
	evidence_urls _text NULL,
	status varchar(255) DEFAULT 'OPEN'::dispute_status NULL,
	admin_notes text NULL,
	resolved_by uuid NULL,
	resolution text NULL,
	resolved_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	evidence text NULL,
	refund_amount numeric(15, 2) NULL,
	CONSTRAINT disputes_pkey PRIMARY KEY (id),
	CONSTRAINT disputes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id),
	CONSTRAINT disputes_raised_by_fkey FOREIGN KEY (raised_by) REFERENCES users(id),
	CONSTRAINT disputes_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES users(id)
);
CREATE INDEX idx_disputes_project_id ON public.disputes USING btree (project_id);
CREATE INDEX idx_disputes_status ON public.disputes USING btree (status);


-- public.messages definition

-- Drop table

-- DROP TABLE messages;

CREATE TABLE messages (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	conversation_id uuid NOT NULL,
	sender_id uuid NOT NULL,
	"content" text NOT NULL,
	created_at timestamptz DEFAULT now() NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (id),
	CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
	CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES users(id)
);
CREATE INDEX idx_messages_conversation_id ON public.messages USING btree (conversation_id, created_at);


-- public.milestones definition

-- Drop table

-- DROP TABLE milestones;

CREATE TABLE milestones (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	project_id uuid NOT NULL,
	title varchar(255) NOT NULL,
	description text NULL,
	amount numeric(15, 2) NOT NULL,
	currency varchar(10) DEFAULT 'USDT'::character varying NULL,
	sequence_order int4 NOT NULL,
	status varchar(255) DEFAULT 'PENDING'::milestone_status NULL,
	due_date timestamp(6) NULL,
	submitted_at timestamptz NULL,
	approved_at timestamptz NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	released_at timestamp(6) NULL,
	approved_by uuid NULL,
	completed_at timestamp(6) NULL,
	CONSTRAINT milestones_pkey PRIMARY KEY (id),
	CONSTRAINT milestones_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
CREATE INDEX idx_milestones_project_id ON public.milestones USING btree (project_id);
CREATE INDEX idx_milestones_sequence ON public.milestones USING btree (project_id, sequence_order);
CREATE INDEX idx_milestones_status ON public.milestones USING btree (project_id, status);


-- public.escrow definition

-- Drop table

-- DROP TABLE escrow;

CREATE TABLE escrow (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	project_id uuid NOT NULL,
	milestone_id uuid NULL,
	amount numeric(15, 2) NOT NULL,
	platform_fee numeric(12, 2) DEFAULT 0 NULL,
	status varchar(255) DEFAULT 'LOCKED'::escrow_status NULL,
	locked_at timestamptz DEFAULT now() NULL,
	released_at timestamptz NULL,
	released_to uuid NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	currency varchar(10) NULL,
	employer_id uuid NOT NULL,
	freelancer_id uuid NOT NULL,
	refunded_at timestamp(6) NULL,
	CONSTRAINT escrow_pkey PRIMARY KEY (id),
	CONSTRAINT escrow_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES milestones(id),
	CONSTRAINT escrow_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id),
	CONSTRAINT escrow_released_to_fkey FOREIGN KEY (released_to) REFERENCES users(id)
);
CREATE INDEX idx_escrow_project_id ON public.escrow USING btree (project_id);
CREATE INDEX idx_escrow_status ON public.escrow USING btree (status);